/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yiting_InstanceFieldAccess */

#ifndef _Included_com_yiting_InstanceFieldAccess
#define _Included_com_yiting_InstanceFieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yiting_InstanceFieldAccess
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yiting_InstanceFieldAccess_accessField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
